### ISSUE TITLE
Mehrere Anschriften?

### ISSUE THREAD

**Issue by mrWinston** [patreu22/Meta-search#11]
Sollten mehrere Anschriften zugelassen werden? ist mir grade beim BAMF aufgefallen, dass die ja tatsächlich mehrere orte haben.

**Comment by JensMeiners** [comment]
Auf der technischen Seite sehe ich hier kein Problem. 
Wie würden wir denn sowas auf unserer Seite darstellen ?
Einmal auf der Seite auf der das Projekt vorgestellt wird und einmal auf der Seite auf der das Projekt eingegeben wird ? können wir da mit javascript was basteln ? Ein textField mit nem kleinen plus icon ?

**Comment by JensMeiners** [comment]
Die verschiedenen Standorte sollten als einzelne Projekte eingetragen werden.
