### ISSUE TITLE
Logo Preview

### ISSUE THREAD

**Issue by JensMeiners** [patreu22/Meta-search#20]
Für das Logo http://beanangel.direct/wp-content/uploads/2015/09/Logo100x100.png
konnte mir die Logo Preview auf der Join Page nichts anzeigen. 
Nachdem ich trotzdem das Projekt erstellt habe wurde das Bild problemlos angezeigt. 

Wenn es Probleme mit dem Feature gibt müssen wir das abschalten, ansonsten verwirrt es nutzer nur und der create button wird nicht gedrückt.

Ich hab das mal dir @dandybudach zugewiesen weil ich glaube dass du das feature eingeführt hast, stimmt das? Vll kannst du das Problem schneller sehen

**Comment by dandybudach** [comment]
Anführungszeichen beim Link wurden nie geschlossen. Fixed in edit und join page
