### ISSUE TITLE
Job zum automatischen Pull von git anlegen

### ISSUE THREAD

**Issue by dandybudach** [patreu22/Meta-search#29]
es sollte evtl. noch ein Job angelegt werden, der automatisch die aktuelle Version aus git auf den server zieht. Einmal täglich würde reichen, denke ich

**Comment by mrWinston** [comment]
Das würde ich eher nicht machen. So können wir uns durch einen unachtsamen
commit ganz schnell die seite zerhauen. Was ist zum beispiel wenn das model
geändert wird? Dann muss noch die datenbank migriert werden. Nur vom server
pullen legt dann die seite lahm.

Dandy Budach notifications@github.com schrieb am Mo., 14. März 2016 19:50:

**Comment by Midnighter** [comment]
Bin ich auch dagegen. Deployment sollte manuell bleiben.
